version: "3"

services:
  app:
    image: my-risevest-app
    ports:
      - "13000:5001"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: imehusoro
      POSTGRES_USER: imehusoro
      POSTGRES_PASSWORD: imehusoro
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
