version: "3"

services:
  app:
    image: risevest-backend-test
    ports:
      - "13000:13000"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: risevest-db
      POSTGRES_USER: imehusoro
      POSTGRES_PASSWORD: imehusoro
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
